# Generated by Django 4.2.7 on 2024-04-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_shop', '0006_product_delete_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.CharField(default='default title', max_length=2000),
        ),
    ]
